version: '3'
services:
  eureka-server:
    image: serviceoutsourcing/server
    restart: always
    ports:
      - 8761:8761

  service-hi:
    image: serviceoutsourcing/user
    restart: always
    ports:
      - 127.0.0.1:8762:8762