version: '3'
services:
  server:
    image: serviceoutsourcing/server
    restart: always
    network_mode: host
    container_name: server

  user:
    image: serviceoutsourcing/user
    restart: always
    network_mode: host
    container_name: user